#!/bin/bash
options=(
hidpi=on
width=4.0
active_color=0xffc0caf5
inactive_color=0xff383838
inactive_background_color=0x02808080
inactive_blur_radius=20
style=round
position=outside
ax_focus=on
stack_color=0xffff00ff
floating_color=0xffff9500
bsp_color=0xff00d4ff
active_only=off
order=below
background_host=companion
animation=none
animation_duration=0.10
animation_easing=ease_in_expo # effects slide only
blacklist="Stats,Dropover,iPhone Mirroring,Passwords,SoundSource,Stickies"
)
/Users/Zeb/Developer/jankyborders/bin/borders "${options[@]}"
