[appearance]

[appearance.themes]
system_theme = false
theme = "adeberry"

[appearance.vertical_tabs]
enabled = true

[appearance.icon]
app_icon = "holographic"

[appearance.text]
notebook_font_size = 14.0
font_size = 13.0
font_name = "Liga SFMono Nerd Font"
ai_font_name = "Liga SFMono Nerd Font"
match_ai_font = true

[general]
default_session_mode = "agent"

[agents]

[agents.third_party]
should_render_cli_agent_toolbar = true

[agents.warp_agent]
is_any_ai_enabled = false

[agents.warp_agent.other]
show_agent_notifications = true
show_conversation_history = true

[code]

[code.editor]
show_code_review_button = true
show_project_explorer = true
show_global_search = true

[warp_drive]
enabled = true

[notifications]
toast_duration_secs = 8
